server:
  port: 8084
  address: 0.0.0.0
  servlet:
    context-path: /

spring:
    motan:
        zookeeper: 192.168.1.148:2181
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.68:3306/mykit_transaction_message_stock?useUnicode=true&characterEncoding=utf8
        username: root
        password: root
   #activemq:
    #   broker-url: tcp://120.76.52.162:61616
    #   user: happylife
    #   password: happylifeplat01
    #   trust-all: true
    #rabbitmq:
    #    host: localhost
    #    port: 5672
    #    username: guest
    #    password: guest
    rocketmq:
        namesrvAddr: 192.168.1.148:9876
        consumerGroupName: inventory
        instanceName: inventory
   #kafka:
      #  consumer:
      #     bootstrap-servers: localhost:9092
      #     group-id: test
      #     auto-offset-reset: earliest
      #     enable-auto-commit: true
      #     auto-commit-interval: 100
      #    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #     value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

mybatis:
  type-aliases-package: io.mykit.transaction.message.demo.motan.inventory.api.entity
  config-location: classpath:mybatis/mybatis-config.xml

logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        io.mykit.transaction.bonuspoint: info
        io.mykit.transaction.lottery: debug
        io.mykit.transaction: debug
        io.netty: info
    path: "./logs"

